runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /(.*\.js)$
  static_files: dist/\1
  upload: dist/.*\.js$
  secure: always

- url: /
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
  http_headers:
    Link: 
      </main.js>;rel=preload;as=script,
      </list-item-main.js>;rel=preload;as=script,
      </list.js>;rel=preload;as=script,
      </api/news>;rel=preload;as=fetch

- url: /(new|ask|show|jobs|favorites)
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
  http_headers:
    Link: 
      </main.js>;rel=preload;as=script,
      </list-item-main.js>;rel=preload;as=script,
      </list.js>;rel=preload;as=script

- url: /item
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
  http_headers:
    Link: 
      </main.js>;rel=preload;as=script,
      </list-item-main.js>;rel=preload;as=script,
      </item-user-main.js>;rel=preload;as=script,
      </item.js>;rel=preload;as=script

- url: /user
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
  http_headers:
    Link: 
      </main.js>;rel=preload;as=script,
      </item-user-main.js>;rel=preload;as=script,
      </user.js>;rel=preload;as=script

- url: /api/(.*)
  script: server.app
  secure: always

skip_files:
- lib/
- node_modules/
- src/
